# Temporary configuration to handle execution ID mismatch issues
# Copy this to config.yaml to enable the fix

# HTTP Server Configuration
http:
  port: 8086
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

# Kafka Configuration
kafka:
  brokers:
    - "globeco-execution-service-kafka:9092"
  topic: "fills"
  consumer_group: "globeco-confirmation-service"
  consumer_timeout: "30s"
  connection_timeout: "10s"
  fetch_timeout: "15s"
  max_retries: 3
  retry_backoff: "100ms"

# Execution Service Configuration
execution_service:
  base_url: "http://globeco-execution-service:8084"
  timeout: "10s"
  max_retries: 3
  retry_backoff: "100ms"
  circuit_breaker:
    failure_threshold: 5
    timeout: "30s"

# Allocation Service Configuration
allocation_service:
  base_url: "http://globeco-allocation-service:8089"
  timeout: "10s"
  max_retries: 3
  retry_backoff: "100ms"
  circuit_breaker:
    failure_threshold: 5
    timeout: "30s"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Metrics Configuration
metrics:
  enabled: true
  path: "/metrics"
  namespace: "confirmation"

# Tracing Configuration
tracing:
  enabled: true
  service_name: "globeco-confirmation-service"
  service_version: "1.0.0"
  exporter: "stdout"

# Performance Configuration
performance:
  max_concurrent_requests: 10
  message_buffer_size: 1000
  worker_pool_size: 5

# Health Check Configuration
health:
  startup_grace_period: "30s"
  check_interval: "10s"

# Validation Configuration - TEMPORARY FIX
validation:
  # Skip execution ID validation for stale messages (TEMPORARY)
  skip_execution_id_validation: false
  # Maximum age of messages to process (in minutes, 0 = no limit)
  max_message_age_minutes: 60
  # Log warnings instead of errors for validation failures (TEMPORARY FIX)
  warn_on_validation_failures: true