apiVersion: v1
kind: Service
metadata:
  name: globeco-confirmation-service
  namespace: globeco
  labels:
    app: globeco-confirmation-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8086"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: globeco-confirmation-service
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP 