apiVersion: v1
kind: Service
metadata:
  name: globeco-confirmation-service
  namespace: globeco
  labels:
    app: globeco-confirmation-service
spec:
  selector:
    app: globeco-confirmation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: ClusterIP 